version: '3.8'
services:
  backend:
    build: ./flask_backend
    command: flask run --host=0.0.0.0 --port=5001
    volumes:
      - ./flask_backend:/app
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
